### ISSUE TITLE
Redis spark conflicts with compiled Redis library

### ISSUE THREAD

**Issue by jeffdupont** [joelcox/codeigniter-redis#32]
The server that I'm trying to run this Spark on has a compiled version of Redis for PHP (https://github.com/nicolasff/phpredis). So naming the class Redis creates a conflict and errors out. Solution would be to rename the spark to PHP-Redis or something along those lines.

**Comment by joelcox** [comment]
Hey Jeff, thanks for your report. I'm kinda wary changing the name; if something else comes along, should the library be renamed again? The proper solution would be to use namespaces, however, CodeIgniter does not currently support these. I believe that renaming the class to CI_Redis is the CI way of doing things. Could you confirm this?

**Comment by danhunsaker** [comment]
Internally, I call it `CI_Redis`, and load it with
`$this->load->library('CI_Redis", '', 'redis');` so that I don't need to
modify any of my other code to keep it working - it's still accessible as
`$this->redis`.

Also, if you are replacing an existing library, the `CI_` prefix is usually
required (since the native classes are usually prefixed this way as well).
`MY_` is preferred for extending classes, though the config file gives an
option for changing this to something else if desired.  The docs don't
specify any recommendations for completely new libraries, but in this case,
`CI_` is probably the best bet.

**Comment by joelcox** [comment]
Thanks for pitching in Dan. I know the message library by @darkhouse does this too: https://github.com/darkhouse/codeigniter-message/blob/master/libraries/Message.php#L11
