### ISSUE TITLE
_auth returns "invalid password" when $password === ''

### ISSUE THREAD

**Issue by beckleyworks** [joelcox/codeigniter-redis#35]
Running PHP 5.3.15. With $config['password'] set to "" (not set), $password argument is actually set and doesn't default to NULL.

I changed if($password !== NULL) to if($password !== NULL && $password !== '')

which works for me. May be a better way.

I'm a GitHub n00b so if there's something I should do here, please let me know. Thanks.

**Comment by danhunsaker** [comment]
It's actually easier to just `if (empty($password)) { foo(); }` - this will call `foo()` when `$password` is null, false, the empty string, or any representation of the number 0.  If it wasn't a function argument, I'd also check with `isset()` first to prevent some really ugly errors about variables that don't exist: `if ( ! isset($password) || empty($password)) { foo(); }`.  But since this is a function argument, it is always actually set, regardless of what it's set to, so the `isset()` check is superfluous in this case.

**Comment by beckleyworks** [comment]
Good call. empty() seems best.

**Comment by joelcox** [comment]
Thanks guys. Messed up in the same commit as the other bug @beckleyworks reported. I'll add a regression test for this one.

773d846e8b9275723ca02d1155013f0ff7e8aba4
